/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlchxd;

/**
 *
 * @author Admin
 */
public class Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public Home_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopControl = new javax.swing.JDesktopPane();
        Label_Main = new javax.swing.JLabel();
        Option_Panel = new javax.swing.JPanel();
        Information_btn = new javax.swing.JButton();
        Customers_btn = new javax.swing.JButton();
        Maintenance_btn = new javax.swing.JButton();
        Employees_btn = new javax.swing.JButton();
        Bill_btn = new javax.swing.JButton();
        Login_btn = new javax.swing.JButton();
        RentBikes_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý cửa hàng xe đạp");
        setPreferredSize(new java.awt.Dimension(1400, 700));

        desktopControl.setPreferredSize(new java.awt.Dimension(1200, 700));

        Label_Main.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Label_Main.setForeground(new java.awt.Color(255, 255, 255));
        Label_Main.setText("QUẢN LÝ CỬA HÀNG XE ĐẠP");

        desktopControl.setLayer(Label_Main, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopControlLayout = new javax.swing.GroupLayout(desktopControl);
        desktopControl.setLayout(desktopControlLayout);
        desktopControlLayout.setHorizontalGroup(
            desktopControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopControlLayout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(Label_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        desktopControlLayout.setVerticalGroup(
            desktopControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Main)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Option_Panel.setBackground(new java.awt.Color(0, 102, 102));
        Option_Panel.setPreferredSize(new java.awt.Dimension(200, 700));

        Information_btn.setText("THÔNG TIN XE ĐẠP");
        Information_btn.setPreferredSize(new java.awt.Dimension(120, 40));
        Information_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Information_btnActionPerformed(evt);
            }
        });

        Customers_btn.setText("QUẢN LÝ KHÁCH HÀNG");
        Customers_btn.setPreferredSize(new java.awt.Dimension(160, 40));
        Customers_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customers_btnActionPerformed(evt);
            }
        });

        Maintenance_btn.setText("QUẢN LÝ BẢO DƯỠNG");
        Maintenance_btn.setPreferredSize(new java.awt.Dimension(160, 40));
        Maintenance_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Maintenance_btnActionPerformed(evt);
            }
        });

        Employees_btn.setText("QUẢN LÝ NHÂN VIÊN");
        Employees_btn.setPreferredSize(new java.awt.Dimension(140, 40));
        Employees_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employees_btnActionPerformed(evt);
            }
        });

        Bill_btn.setText("QUẢN LÝ BÁN HÀNG");
        Bill_btn.setPreferredSize(new java.awt.Dimension(120, 40));
        Bill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_btnActionPerformed(evt);
            }
        });

        Login_btn.setText("Đăng nhập");
        Login_btn.setPreferredSize(new java.awt.Dimension(100, 40));
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        RentBikes_btn.setText("QUẢN LÝ THUÊ XE");
        RentBikes_btn.setPreferredSize(new java.awt.Dimension(140, 40));
        RentBikes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentBikes_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Option_PanelLayout = new javax.swing.GroupLayout(Option_Panel);
        Option_Panel.setLayout(Option_PanelLayout);
        Option_PanelLayout.setHorizontalGroup(
            Option_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option_PanelLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(Option_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Customers_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(Information_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Employees_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bill_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RentBikes_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Maintenance_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Login_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Option_PanelLayout.setVerticalGroup(
            Option_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(Information_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Customers_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Employees_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bill_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RentBikes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Maintenance_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Option_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopControl, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Option_Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desktopControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Information_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Information_btnActionPerformed
        Infor_Bikes Infor = new Infor_Bikes();
        desktopControl.add(Infor);
        Infor.setVisible(true);
        Infor.moveToFront();
        
    }//GEN-LAST:event_Information_btnActionPerformed

    private void Customers_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customers_btnActionPerformed
        Customers custom = new Customers();
        desktopControl.add(custom);
        // Hiển thị cửa sổ đăng nhập
        custom.setVisible(true);
        custom.moveToFront();
    }//GEN-LAST:event_Customers_btnActionPerformed

    private void Maintenance_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Maintenance_btnActionPerformed
        Maintenance_ChuaXong bike = new Maintenance_ChuaXong();
        desktopControl.add(bike);
        bike.setVisible(true);
        bike.moveToFront();
    }//GEN-LAST:event_Maintenance_btnActionPerformed

    private void Bill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_btnActionPerformed
        Payments pay= new Payments();
        desktopControl.add(pay);
        pay.setVisible(true);
        pay.moveToFront();
    }//GEN-LAST:event_Bill_btnActionPerformed

    private void Employees_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employees_btnActionPerformed
        Employees employee = new Employees();
        desktopControl.add(employee);
        employee.setVisible(true);
        employee.moveToFront();
    }//GEN-LAST:event_Employees_btnActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_btnActionPerformed

    private void RentBikes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentBikes_btnActionPerformed
        Rent_Bikes rent = new Rent_Bikes();
        desktopControl.add(rent);
        rent.setVisible(true);
        rent.moveToFront();
    }//GEN-LAST:event_RentBikes_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bill_btn;
    private javax.swing.JButton Customers_btn;
    private javax.swing.JButton Employees_btn;
    private javax.swing.JButton Information_btn;
    private javax.swing.JLabel Label_Main;
    private javax.swing.JButton Login_btn;
    private javax.swing.JButton Maintenance_btn;
    private javax.swing.JPanel Option_Panel;
    private javax.swing.JButton RentBikes_btn;
    private javax.swing.JDesktopPane desktopControl;
    // End of variables declaration//GEN-END:variables
}
