/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlchxd;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Admin
 */
public class Main_withoutSignIn extends javax.swing.JFrame {

    /**
     * Creates new form Main_SignIn
     */
    public Main_withoutSignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopControl = new javax.swing.JDesktopPane();
        Option_Panel = new javax.swing.JPanel();
        Information_btn = new javax.swing.JButton();
        Customers_btn = new javax.swing.JButton();
        Maintenance_btn = new javax.swing.JButton();
        Employees_btn = new javax.swing.JButton();
        Bill_btn = new javax.swing.JButton();
        Login_btn = new javax.swing.JButton();
        RentBikes_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Label_Main2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Label_Main1 = new javax.swing.JLabel();
        Label_Main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopControl.setBackground(new java.awt.Color(153, 255, 255));
        desktopControl.setPreferredSize(new java.awt.Dimension(1200, 700));

        javax.swing.GroupLayout desktopControlLayout = new javax.swing.GroupLayout(desktopControl);
        desktopControl.setLayout(desktopControlLayout);
        desktopControlLayout.setHorizontalGroup(
            desktopControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopControlLayout.setVerticalGroup(
            desktopControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        Option_Panel.setBackground(new java.awt.Color(0, 102, 102));
        Option_Panel.setPreferredSize(new java.awt.Dimension(200, 700));

        Information_btn.setText("THÔNG TIN XE ĐẠP");
        Information_btn.setPreferredSize(new java.awt.Dimension(120, 40));
        Information_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Information_btnActionPerformed(evt);
            }
        });

        Customers_btn.setText("QUẢN LÝ KHÁCH HÀNG");
        Customers_btn.setPreferredSize(new java.awt.Dimension(160, 40));
        Customers_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customers_btnActionPerformed(evt);
            }
        });

        Maintenance_btn.setText("QUẢN LÝ BẢO DƯỠNG");
        Maintenance_btn.setPreferredSize(new java.awt.Dimension(160, 40));
        Maintenance_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Maintenance_btnActionPerformed(evt);
            }
        });

        Employees_btn.setText("QUẢN LÝ NHÂN VIÊN");
        Employees_btn.setPreferredSize(new java.awt.Dimension(140, 40));
        Employees_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employees_btnActionPerformed(evt);
            }
        });

        Bill_btn.setText("QUẢN LÝ BÁN HÀNG");
        Bill_btn.setPreferredSize(new java.awt.Dimension(120, 40));
        Bill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_btnActionPerformed(evt);
            }
        });

        Login_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Login_btn.setText("Đăng nhập");
        Login_btn.setPreferredSize(new java.awt.Dimension(100, 40));
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        RentBikes_btn.setText("QUẢN LÝ THUÊ XE");
        RentBikes_btn.setPreferredSize(new java.awt.Dimension(140, 40));
        RentBikes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentBikes_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Option_PanelLayout = new javax.swing.GroupLayout(Option_Panel);
        Option_Panel.setLayout(Option_PanelLayout);
        Option_PanelLayout.setHorizontalGroup(
            Option_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option_PanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Option_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Customers_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Information_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Employees_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bill_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RentBikes_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Maintenance_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        Option_PanelLayout.setVerticalGroup(
            Option_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option_PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Information_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Customers_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Employees_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bill_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RentBikes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Maintenance_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logo3.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 200));

        Label_Main2.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Label_Main2.setForeground(new java.awt.Color(255, 255, 255));
        Label_Main2.setText("HUY NAM");

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THƯƠNG HIỆU UY TÍN HÀNG ĐẦU VIỆT NAM");

        Label_Main1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Label_Main1.setForeground(new java.awt.Color(255, 255, 255));
        Label_Main1.setText("QUẢN LÝ CỬA HÀNG XE ĐẠP ");

        Label_Main.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Label_Main.setForeground(new java.awt.Color(255, 255, 255));
        Label_Main.setText("HUY NAM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(Label_Main1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Main))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(Label_Main2))
                            .addComponent(jLabel1))))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Main)
                    .addComponent(Label_Main1))
                .addGap(140, 140, 140)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Main2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Option_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(desktopControl, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(desktopControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Option_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Information_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Information_btnActionPerformed
        JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập để sử dụng tính năng");

    }//GEN-LAST:event_Information_btnActionPerformed

    private void Customers_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customers_btnActionPerformed
        JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập để sử dụng tính năng");
    }//GEN-LAST:event_Customers_btnActionPerformed

    private void Maintenance_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Maintenance_btnActionPerformed
        JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập để sử dụng tính năng");
    }//GEN-LAST:event_Maintenance_btnActionPerformed

    private void Employees_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employees_btnActionPerformed
        JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập để sử dụng tính năng");
    }//GEN-LAST:event_Employees_btnActionPerformed

    private void Bill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_btnActionPerformed
        JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập để sử dụng tính năng");
    }//GEN-LAST:event_Bill_btnActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        javax.swing.JFrame frame = new javax.swing.JFrame("Login Form");
        frame.setContentPane(new FrmLogin()); // Truyền MainFrm vào Login
        frame.setSize(1000, 500);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        frame.setVisible(true); // Hiển thị JFrame mới
    }//GEN-LAST:event_Login_btnActionPerformed

    private void RentBikes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentBikes_btnActionPerformed
        JOptionPane.showMessageDialog(this, "Bạn phải đăng nhập để sử dụng tính năng");
    }//GEN-LAST:event_RentBikes_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_withoutSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_withoutSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_withoutSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_withoutSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_withoutSignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Accounts_label;
    private javax.swing.JButton Bill_btn;
    private javax.swing.JButton Customers_btn;
    private javax.swing.JButton Employees_btn;
    private javax.swing.JButton Information_btn;
    private javax.swing.JLabel Label_Main;
    private javax.swing.JLabel Label_Main1;
    private javax.swing.JLabel Label_Main2;
    private javax.swing.JButton Login_btn;
    private javax.swing.JButton Login_btn1;
    private javax.swing.JButton Maintenance_btn;
    private javax.swing.JPanel Option_Panel;
    private javax.swing.JLabel Position_label;
    private javax.swing.JButton RentBikes_btn;
    private javax.swing.JDesktopPane desktopControl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
